apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::767397856049:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-O4vUS2nh7lDY
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-pod-reader
      userarn: arn:aws:iam::767397856049:user/rama
      username: rama
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::767397856049:user/raheem
      username: raheem
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  uid: 9aa9d5e0-2af8-4448-a003-383572ac3c5b


