apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::767397856049:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-ii57BT1CUpKl
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-pod-reader
      userarn: arn:aws:iam::767397856049:user/rama
      username: rama
    - groups:
      - roboshop-admin
      userarn: arn:aws:iam::767397856049:user/raheem
      username: raheem
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  uid: 1084f32b-6770-4688-ac33-8e692540fe3e

